path_into_db = 'C:/Users/james.izzard/Dropbox/pydiet/database/'
ingredient_db_path = path_into_db + 'ingredients/'
recipe_db_path = path_into_db + 'recipes/'
meal_goals_db_path = path_into_db + 'goals/meal_goals/'
day_goals_db_path = path_into_db + 'goals/day_goals/'
global_day_goals_db_path = path_into_db + 'goals/global_day_goals.json'
